data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
subSetData <- data[data$Date %in% c("1/2/2007","2/2/2007")
gap <- as.numeric(subSetData[,"Global_active_power"])  
png(file ="rplot1.png", width = 480, height = 480)
hist(gap, col = "red",main = "Global Active Power", xlab = "Global Active Power (kilowatts)", ylab = "Frequency")
dev.off()